using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DIYShopSys
{
    public partial class RestockItems : Form
    {
        MainMenu mainMenu;
        DataSet dataset;
        Double total;
        int SupplierId;
        public RestockItems()
        {
            InitializeComponent();
        }
        public RestockItems(MainMenu main)
        {
            InitializeComponent();
            this.mainMenu = main;
            main.Hide();
            resetDataset();
            /*used this to hide columns
             * https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/remove-autogenerated-columns-from-a-wf-datagridview-control?view=netframeworkdesktop-4.8
                */
            Items.Columns[0].Visible = false;
            for (int i = 0; i < dataset.Tables[0].Rows.Count; i++)
            {
                if (!Supplier.Items.Contains(dataset.Tables[0].Rows[i][0].ToString() + "-" + dataset.Tables[0].Rows[i][1].ToString()))
                {
                    Supplier.Items.Add(dataset.Tables[0].Rows[i][0].ToString() + "-" + dataset.Tables[0].Rows[i][1].ToString());
                }
            }
        }
        private void Supplier_SelectedIndexChanged(object sender, EventArgs e)
        {
            for (int i = 0; i < dataset.Tables[0].Rows.Count; i++)
            {
                if (Supplier.SelectedItem.Equals(dataset.Tables[0].Rows[i][0] + "-" + dataset.Tables[0].Rows[i][1]))
                {
                    total = Convert.ToDouble(dataset.Tables[0].Rows[i][2]);
                    TotalLabel.Text = "total = " + total;
                    //found out how to filter datasets from here https://stackoverflow.com/questions/5843537/filtering-datagridview-without-changing-datasource
                    dataset.Tables[0].DefaultView.RowFilter = "Supplier_id = " + dataset.Tables[0].Rows[i][0];
                    Items.Columns[0].Visible = false;
                    SupplierId = Convert.ToInt32(dataset.Tables[0].Rows[i][0]);
                }
            }
            GroupBox.Visible = true;
        }
        private void AddToBasket_Click(object sender, EventArgs e)
        {
            if (Items.SelectedRows.Count == 1)
            {
                if (Basket.Rows.Count > 0)
                {
                    for (int i = 0; i < Basket.Rows.Count; i++)
                    {
                        //source for selectectedRows.index[2] second answer :https://stackoverflow.com/questions/3578144/index-of-currently-selected-row-in-datagridview
                        if (Basket.Rows[i].Cells[0].Value.ToString().Equals(Items.SelectedRows[0].Cells[3].Value.ToString()))
                        {
                            dataset.Tables[1].Rows[i][3] = Convert.ToInt32(dataset.Tables[1].Rows[Items.SelectedRows[0].Index][3]) + 1;
                            total += Convert.ToDouble(Items.SelectedRows[0].Cells[5].Value.ToString());
                            TotalLabel.Text = "total = " + total;
                            return;
                        }
                    }
                    addToBasket();
                }
                else
                {
                    addToBasket();
                }
            }
        }
        private void addToBasket()
        {
            DataRow row = dataset.Tables[1].NewRow();
            //id
            row[0] = Items.SelectedRows[0].Cells[3].Value.ToString();
            //name
            row[1] = Items.SelectedRows[0].Cells[4].Value.ToString();
            //price
            row[2] = Items.SelectedRows[0].Cells[5].Value.ToString();
            //quantity
            row[3] = 1;
            dataset.Tables[1].Rows.Add(row);
            total += Convert.ToDouble(Items.SelectedRows[0].Cells[5].Value.ToString());
            TotalLabel.Text = "total = " + total;
        }
        private void RemoveItemFromBasket_Click(object sender, EventArgs e)
        {
            if (Basket.SelectedRows.Count == 1)
            {
                total -= Convert.ToDouble(Basket.SelectedRows[0].Cells[2].Value.ToString());
                TotalLabel.Text = "total = " + total;
                if (Convert.ToInt32(dataset.Tables[1].Rows[Basket.SelectedRows[0].Index][3]) == 1)
                {
                    dataset.Tables[1].Rows.RemoveAt(Basket.SelectedRows[0].Index);
                }
                else
                {
                    dataset.Tables[1].Rows[0][2] = Convert.ToInt32(dataset.Tables[1].Rows[Basket.SelectedRows[0].Index][3]) - 1;
                }
            }
        }

        private void BuyButton_Click(object sender, EventArgs e)
        {
            //messagebox yes no from https://stackoverflow.com/questions/3036829/how-do-i-create-a-message-box-with-yes-no-choices-and-a-dialogresult
            DialogResult dialogresult = MessageBox.Show("Are You Sure", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (dialogresult == DialogResult.Yes)
            {
                new Sql().AddOrUpdate("insert into orders values(" + new Sql().GetNextOrderId() + ",sysdate," + total + "," + SupplierId + ")");
                for (int i = 0; i < Basket.Rows.Count; i++) {
                    new Sql().AddOrUpdate("update items set quantity = quantity + " + Basket.Rows[i].Cells[3].Value + "where item_id = " + Basket.Rows[i].Cells[0].Value);
                }
                MessageBox.Show("Items Ordered", "Items Ordered", MessageBoxButtons.OK);
                resetDataset();
            }
        }
        private void resetDataset()
        {
            //how to create a datatable https://learn.microsoft.com/en-us/dotnet/api/system.data.datatable?view=net-7.0
            this.dataset = new Sql().GetDataSet("select items.supplier_id, supplier_name, delivery_fee,item_id,item_name, item_cost from items inner join suppliers on suppliers.supplier_id = items.supplier_id where item_status = 'a'");
            dataset.Tables[0].Columns[1].ColumnName = "Supplier"; 
            dataset.Tables[0].Columns[2].ColumnName = "Delivery Fee";
            dataset.Tables[0].Columns[4].ColumnName = "Item";
            dataset.Tables[0].Columns[5].ColumnName = "Cost";
            //creating basket table
            DataTable table = new DataTable("Basket");
            DataColumn column;
            //id
            column = new DataColumn();
            column.DataType = typeof(int);
            column.ColumnName = "item Id";
            table.Columns.Add(column);
            //name
            column = new DataColumn();
            column.DataType = typeof(string);
            column.ColumnName = "Name";
            column.ReadOnly = true;
            table.Columns.Add(column);
            //price
            column = new DataColumn();
            column.DataType = typeof(double);
            column.ColumnName = "Cost";
            table.Columns.Add(column);
            //Quantity
            column = new DataColumn();
            column.DataType = typeof(int);
            column.ColumnName = "Quantity";
            table.Columns.Add(column);

            dataset.Tables.Add(table);

            Items.DataSource = dataset.Tables[0];
            Basket.DataSource = dataset.Tables[1];
            total = 0;
            Items.Columns[3].Visible = false;
            Basket.Columns[0].Visible = false;
            Supplier.SelectedIndex = -1;
        }
        // closing form
        private void RestockItems_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (mainMenu.Visible == false)
            {
                Application.Exit();
            }
        }
        //returns to main menu
        private void ReturnButton_Click(object sender, EventArgs e)
        {
            mainMenu.Show();
            this.Close();
        }
    }
}
